name: 'Extract Parameters'
description: 'Extract parameters for image building'

branding:
  icon: 'heart'
  color: 'red'

inputs:
  php_version:
    description: 'PHP version in form: 8.3.1'
    required: true
  php_type:
    description: 'PHP build type in form: fpm'
    required: false
    default: 'fpm'

outputs:
  context:
    description: 'Image context'

runs:
  using: 'node20'
  main: 'dist/index.js'
