name: 'Extract Image Context'
description: 'Extract image context for PHP images building'

inputs:
  php_version:
    description: 'PHP version in form: 8.3.1'
    required: true
  php_type:
    description: 'PHP build type in form: fpm'
    required: false
    default: 'fpm'
  php_ext_namespace:
    description: 'DockerHub namespace of PHPExt images'
    required: false

outputs:
  context:
    description: 'Image context'

runs:
  using: 'node20'
  main: 'dist/index.js'
