name: Build And Push Images

on:
  workflow_call:
    inputs:
      php_version:
        required: true
        type: string
      environment:
        description: 'Environment to build images against'
        type: string
        required: true

jobs:
  image_context:
    name: Generate Image Context
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    outputs:
      matrix: ${{ steps.extract_context.outputs.context }}

    env:
      PHP_VERSION: ${{ inputs.php_version }}
      DOCKERHUB_NAMESPACE: ${{ vars.PUSH_TO_DOCKERHUB == 'true' && vars.DOCKERHUB_NAMESPACE || '' }}

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Extract image context
        id: extract_context
        uses: ./.github/actions/extract-image-context-action
        with:
          php_version: ${{ env.PHP_VERSION }}
          php_ext_suffix: ext
          php_ext_namespace: ${{ env.DOCKERHUB_NAMESPACE }}
          php_type: ${{ vars.PHP_TYPE }}

  build_image:
    name: Build And Push Image
    needs: ['image_context']
    if: ${{ fromJSON(needs.image_context.outputs.matrix)[0] != null  }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    strategy:
      matrix:
        include: ${{ fromJSON(needs.image_context.outputs.matrix) }}

    permissions:
      packages: write
      contents: read
      id-token: write
      attestations: write

    env:
      IMAGE_NAME: ghcr.io/${{ github.actor }}/php
      IMAGE_NAME_DOCKER: ${{ vars.PUSH_TO_DOCKERHUB == 'true' && format('docker.io/{0}/php', vars.DOCKERHUB_NAMESPACE) || '' }}
      EXT_LIST: ${{ vars.EXT_LIST }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        if: ${{ vars.PUSH_TO_DOCKERHUB == 'true'  }}
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.IMAGE_NAME_DOCKER }}
            ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ matrix.phpExtTag }},enable=true

      - name: Build image for testing
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.dockerFile }}
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            IMAGETAG=${{ matrix.phpTag }}
            EXT_LIST=${{ vars.EXT_LIST }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test Docker image
        run: |
          echo "::group::Checking image libraries ${{ matrix.phpExtTag }}"
          LIBS=$(docker run --rm ${{ env.IMAGE_NAME }}:${{ matrix.phpExtTag }} php -m)
          for lib in $EXT_LIST; do \
            if [[ $(echo "${LIBS[@]}" | fgrep -wi "$lib") ]]; \
              then echo "::debug::OK: $lib"; \
              else echo "::error title={$lib}::{$lib library may not have been installed}"; \
            fi; \
          done
          echo "::endgroup::"

      - name: Build and push the image
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.dockerFile }}
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }}
          build-args: |
            IMAGETAG=${{ matrix.phpTag }}
            EXT_LIST=${{ vars.EXT_LIST }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Generate artifact attestation (GitHub)
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: true

      - name: Generate artifact attestation (DockerHub)
        if: ${{ vars.PUSH_TO_DOCKERHUB == 'true'  }}
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.IMAGE_NAME_DOCKER}}
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: false
