name: Workflow Dispatch Build And Push Images

on:
  workflow_dispatch:
    inputs:
      php_version:
        required: true
        type: string

      environment:
        description: 'Environment to build images against'
        type: environment
        required: true

jobs:
  image_context:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Extract Image Context
        id: extract_context
        uses: ./.github/actions/extract-parameters
        with:
          php_version: ${{ env.PHP_VERSION }}
          php_type: 'fpm'
        env:
          PHP_VERSION: ${{ inputs.php_version }}
          ENVIRONMENT: ${{ inputs.environment }}
      - name: Print
        env:
          CONTEXT: "${{ steps.extract_context.outputs.context }}"
        run: echo "Matrix value $CONTEXT"


