name: Workflow Dispatch

on:
  workflow_dispatch:
    inputs:
      php_version:
        description: 'PHP version'
        required: true
        type: string

      environment:
        description: 'Environment'
        type: environment
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      PHP_EXT_NAMESPACE: ${{ vars.PUSH_TO_DOCKERHUB == 'true' && vars.DOCKERHUB_NAMESPACE || '' }}
    steps:
      - name: THE TEST
        run: |
          echo "PHP_EXT_NAMESPACE: ${{ env.PHP_EXT_NAMESPACE }};"
  # build_images:
  #   uses: ./.github/workflows/build-and-push-images.yml
  #   secrets: inherit
  #   with:
  #     php_version: ${{ inputs.PHP_VERSION }}
  #     environment: ${{ inputs.environment }}

  #   permissions:
  #     packages: write
  #     contents: read
  #     id-token: write
  #     attestations: write
