name: Workflow Dispatch Build And Push Images

on:
  workflow_dispatch:
    inputs:
      php_version:
        required: true
        type: string

      environment:
        description: 'Environment to build images against'
        type: environment
        required: true

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Get Inputs
        env:
          PHP_VERSION: ${{ inputs.php_version }}
          ENVIRONMENT: ${{ inputs.environment }}
        run: |
          echo "Ref: ${{ github.ref }}"
          echo "Version: $PHP_VERSION"
          echo "Environment: $ENVIRONMENT"
      - name: Scan for PHP configurations
        id: scan
        uses: ./actions/extract-parameters
        with:
          php-version: ${{ env.PHP_VERSION }}
          php-type: 'fpm'

      - name: Print
        run: "echo 'Recent updates: ${{ steps.scan.outputs.tags }}'"

