name: Workflow Dispatch Build And Push Images

on:
  workflow_dispatch:
    inputs:
      php_version:
        required: true
        type: string

      environment:
        description: 'Environment to build images against'
        type: environment
        required: true
env:
  PHP_VERSION: ${{ inputs.php_version }}
  ENVIRONMENT: ${{ inputs.environment }}

jobs:
  image_context:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.extract_context.outputs.context }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Extract Image Context
        id: extract_context
        uses: ./.github/actions/extract-image-context-action
        with:
          php_version: ${{ env.PHP_VERSION }}
          environment: ${{ env.ENVIRONMENT }}
          php_type: 'fpm'
      - name: Print
        env:
          CONTEXT: "${{ steps.extract_context.outputs.context }}"
        run: echo "Matrix value $CONTEXT"
  build_image:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: ['image_context']
    strategy:
      matrix:
        include: ${{ fromJSON(needs.image_context.outputs.matrix) }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Print context
        run: |
          echo "image ${{ matrix.image }} / file ${{ matrix.file }}"


