name: Workflow Dispatch Build And Push Images

on:
  workflow_dispatch:
    inputs:
      php_version:
        required: true
        type: string

      environment:
        description: 'Environment to build images against'
        type: environment
        required: true

jobs:
  image-context:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.scan.outputs.image-contex }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Scan for PHP configurations
        id: scan
        uses: ./.github/actions/extract-parameters
        with:
          php-version: ${{ env.PHP_VERSION }}
          php-type: 'fpm'

        env:
          PHP_VERSION: ${{ inputs.php_version }}
          ENVIRONMENT: ${{ inputs.environment }}
  build-image:
    runs-on: ubuntu-latest
    needs: ['image-context']
    strategy:
      matrix:
        include: ${{ fromJSON(needs.image-context.outputs.matrix) }}
    steps:
      - name: Print context
        run: |
          echo "image ${{ matrix.image }} / file ${{ matrix.file }}"


